### ISSUE TITLE
Star OTTO Light firmware as-shipped isn't reflected in this repo

### ISSUE THREAD

**Issue by MartyMacGyver** [arduino-org/arduino-firmware-wifilink#26]
The firmware on my Star OTTO Light is - out of the box - newer than anything in this repo currently (I see `wifilink - 1.0.1 (20170509)`.

This appears to correspond to the version on the `test` branch here:
https://github.com/andrea-83/arduino-firmware-esp/tree/test

Whatever the origin, the code that's shipping on these boards should be pulled into this repo as well.

**Comment by sergiotomasello** [comment]
sure, take a look [here](https://github.com/arduino-org/arduino-firmware-wifilink/releases/tag/1.0.1)

**Comment by MartyMacGyver** [comment]
Thank you!
