### ISSUE TITLE
Comptability with blynk.cc

### ISSUE THREAD

**Issue by yorelk** [arduino-org/arduino-firmware-wifilink#32]
Hey, does this firmware enable the tcp protocol. 
I want to use a Arduino uno wifi dev ed with Blynk.CC library.
Thank's

**Comment by jandrassy** [comment]
functionality is very similar to Ethernet and Wifi library. look at the examples of the WiFi Link library

**Comment by yorelk** [comment]
Thank you, i take look after flashing fimrware

**Comment by yorelk** [comment]
Hey, i'can't flash the firmware...
What is the correct way to flash it ?
Thank's a lot

**Comment by jandrassy** [comment]
#23
